server:
  port: 9001
spring:
  application:
    name: service-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    loadbalancer:
      configurations: zone-preference

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

github:
  client:
    url: https://api.github.com

# feign 配置
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 3000
