server:
  port: 8081  # 服务端口

spring:
  application:
    name: service-provider  # 服务名称，用于服务发现
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # 注册中心地址
  instance:
    prefer-ip-address: true  # 注册时使用IP地址
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: ${spring.application.name}:${server.port}
